services:
  nginxlog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginxlog-LO
    restart: always
    volumes:
      - /var/log/docker/docker-nginx-LO.log:/var/log/nginx/nginx.log:ro
      - ./config:/app/config:ro
      - ./alerts:/app/alerts  # アラートファイル出力用ボリューム
    environment:
      # Java環境変数の設定（デバッグモード有効）
      - JAVA_OPTS=-Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Tokyo
      - NGINX_LOG_DEBUG=true
      - LOG_PATH=/var/log/nginx/nginx.log
      - SECURE_CONFIG_PATH=/run/secrets/db_config_enc
      - KEY_PATH=/run/secrets/db_secret_key
      - ATTACK_PATTERNS_PATH=/app/config/attack_patterns.json
      - SERVERS_CONFIG_PATH=/app/config/servers.conf
      - ALERTS_OUTPUT_PATH=/app/alerts  # アラートファイル出力パス
    secrets:
      - db_config_enc
      - db_secret_key
    networks:
      mysql_network:
        ipv4_address: 172.18.1.7
      NLL_network:
        ipv4_address: 172.18.7.2

secrets:
  db_config_enc:
    file: ./db_config.enc
  db_secret_key:
    file: ./secret.key

networks:
  mysql_network:
    external: true
  NLL_network:
    external: true
