services:
  nginxlog:
    build: .
    container_name: nginxlog-LO
    restart: always
    volumes:
      - /var/log/docker/docker-nginx-LO.log:/var/log/nginx/nginx.log:ro
      - ./attack_patterns.json:/run/secrets/attack_patterns.json:ro
      - ./modules:/app/modules:ro
    environment:
      - PYTHONUNBUFFERED=1
    secrets:
      - db_config_enc
      - db_secret_key
    networks:
      mysql_network:
        ipv4_address: 172.18.1.7
      NLL_network:
        ipv4_address: 172.18.7.2

secrets:
  db_config_enc:
    file: ./db_config.enc
  db_secret_key:
    file: ./secret.key
networks:
  mysql_network:
    external: true
  NLL_network:
    external: true

